# Generated by Django 5.1.6 on 2025-04-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_journal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
